name: Run Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci

      - run: npx nx format:check
      - run: npx nx affected --GuessTheSong=test --parallel=3 --ci --code-coverage
      - run: npx nx affected --data-api=test --parallel=3 --ci --code-coverage
      - run: npx nx affected --GuessTheSong=build --parallel=3
      - run: npx nx affected --data-api=build --parallel=3
      - run: npx nx affected --neo4j=build --parallel=3
